setRule.ambientLight(packColor(0.5, 0.5, 0.5, 1));
setRule.attackMode(false);
setRule.blockDamage(Teams.crux, 0.5);
setRule.blockHealth(Teams.crux, 0.7);
setRule.buildSpeed(Teams.sharded, 1.5);
setRule.currentWaveTime(600);
setRule.dropZoneRadius(15);
setRule.enemyCoreBuildRadius(50);
setRule.lighting(false);
setRule.mapArea({ x: 0, y: 0, width: 200, height: 200 });
setRule.rtsMinSquad(Teams.crux, 16);
setRule.rtsMinWeight(Teams.crux, 20);
setRule.solarMultiplier(100);
setRule.unitBuildSpeed(Teams.sharded, 2);
setRule.unitCap(20);
setRule.unitDamage(Teams.crux, 0.8);
setRule.wave(1);
setRule.waveSending(true);
setRule.waveSpacing(256);
setRule.waveTimer(true);
setRule.waves(true);
