export * from "./Function";
export * from "./Math";
export * from "./Other";
export * as commands from "./commands";
export * from "./Memory";
export { NamespaceMacro, VarsNamespace } from "./Namespace";
export * from "./DynamicArray";
export * from "./Unchecked";
export * from "./GetBuildings";
export * from "./GetGlobal";
export * from "./GetColor";
export * from "./Marker";
