export * from "./Program"
export * from "./VariableDeclaration"
export * from "./Literal"
export * from "./OperationExpressions"
export * from "./Identifier"
export * from "./Statements"
export * from "./IfStatement"
export * from "./WhileStatement"
export * from "./ForStatement"
// export * from "./Functions"