module.exports = {
  "==": ["equal", (a, b) => a == b],
  "!=": ["notEqual", (a, b) => a != b],
  "!==": ["notEqual", (a, b) => a !== b],
  "<": ["lessThan", (a, b) => a < b],
  ">": ["greaterThan", (a, b) => a > b],
  "<=": ["lessThanEq", (a, b) => a <= b],
  ">=": ["greaterThanEq", (a, b) => a >= b],
  "+": ["add", (a, b) => a + b],
  "-": ["sub", (a, b) => (b ? a - b : -a)],
  "*": ["mul", (a, b) => a * b],
  "/": ["div", (a, b) => a / b],
  "%": ["mod", (a, b) => a % b],
  "**": ["pow", (a, b) => a ** b],
  "&&": ["land", (a, b) => a && b],
  "||": ["or", (a, b) => a || b],
  "&": ["and", (a, b) => a & b],
  "|": ["or", (a, b) => a | b],
  "^": ["xor", (a, b) => a ^ b],
  ">>": ["shr", (a, b) => a >> b],
  "<<": ["shl", (a, b) => a << b],
  "!": ["not", (a) => !a],
  "~": ["flip", (a) => ~a],
  "++": ["add"],
  "--": ["sub"],
};
