name: ci

on:
  push:
    branches-ignore: ["ci"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
      - uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile
      - run: pnpm -C compiler clean
      - run: pnpm -C compiler/test exec tsc #typecheck tests
      - run: pnpm -C compiler coverage
