name: netlify-publish
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  publish:
    environment: netlify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: "https://registry.npmjs.org"
          cache: pnpm
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          install_command: pnpm i --frozen-lockfile
          build_command: pnpm -C compiler build && pnpm -C website build
          build_directory: website/docs/.vitepress/dist
          NETLIFY_SITE_ID: acf4f3cb-5776-415f-b3f4-9d247b5a6253
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_DEPLOY_TO_PROD: true
