name: npm-publish
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  publish:
    environment: npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v6

      - run: pnpm install --frozen-lockfile
      - run: pnpm -C compiler/test exec tsc #typecheck tests
      - run: pnpm -C compiler coverage
      - run: npm publish --access public
        working-directory: ./compiler
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_AUTH_TOKEN }}
